### ISSUE TITLE
Server Sync Error

### ISSUE THREAD

**Issue by eppersonadam** [Turbero/valheim-KillMeForMyPower#1]
[Info   :   BepInEx] Loading [Kill Me For My Power 1.0.3]
TypeLoadException: Could not load type of field 'KillMeForMyPower.ConfigurationFile:ConfigSync' (11) due to: Could not load file or assembly 'ServerSync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by Turbero** [comment]
Hi! Very sorry, I picked up the wrong dll without ServerSync into the mod file.

I'll reupload now in 1.0.4. Thanks for warning!!!!

**Comment by Turbero** [comment]
updated 1.0.4. 

https://thunderstore.io/c/valheim/p/turbero/KillMeForMyPower/

Thanks again!
